module.exports = [
  {
    "id": "advisor",
    "name": "Ashleigh Bingham",
    "pronouns": "She/Her",
    "position": "Advisor",
    "image": "/images/faces/Bing.jpg",
    "bio": ["Dr. Ashleigh “Bing” Bingham (she/her/hers) joined the Virginia Tech and Cultural and Community Center staff during the fall of 2019 and serves as the Director for the LGBTQ+ Resource Center and advisor of HokiePRIDE. She will be working to support the mental, emotional, social, and physical wellbeing of lesbian, gay, bisexual, transgender, and queer Hokies by creating space and providing resources for marginalized individuals within the queer community and by facilitating learning opportunities for students, faculty, and staff.",
    "Dr. Bing received her Bachelor’s degree in Psychology, her Master’s degree in Social Psychology, and her Doctorate degree in Higher Education from Ball State University in Muncie, Indiana. Previously, Dr. Bing worked with Ball State University’s Women’s & Gender Studies program teaching classes and overseeing their marketing, promotion, and recruitment efforts.",],
    "duties": [
                "Be the Director of the LGBTQ+ Resource Center at Virginia Tech, who is a staff member of the Cultural & Community Centers;",
                "Stay informed of the actions and decisions of the organization;",
                "Support student learning and leadership by engaging officers to develop their leadership skills;",
                "Attend events regularly throughout the year, when able;",
                "Assist in organization leadership continuity between officer transitions;",
                "Ensure financial obligations are being met when the Finance Chair is unable to; and",
                "Serve as a liaison between Student Affairs university staff and HokiePRIDE when requested."
               ],
    "strengths": ["Individualization",
                  "Strategic",
                  "Adaptability",
                  "Achiever",
                  "Context"],
    "funfacts": [ "My partner and I have two Maine Coon cats.",
								  "I ran a gender non-conforming fashion blog called “I Dream of Dapper” in college.",
								  "I’m obsessed with historical lesbians.",]
  },
  {
    "id": "cp1",
    "name": "Nathaniel Soss",
    "pronouns": "He/Him",
    "position": "Co-President",
    "image": "/images/faces/Nathaniel.jpg",
    "bio": "I'm a gay computer nerd who loves listening to and composing music, watching cartoons, and playing videogames. I'm also involved with the Galipatia Living Learning Community, this year as a mentor. My major is Computer Science. ",
    "duties": [
                "Represent the organization and maintain contacts with the university administration, other campus organizations, and off-campus persons, organizations, and institutions;",
                 "Meet regularly with faculty advisor to coordinate official efforts of the organization;",
                 "Represent or delegate someone to represent the organization on university committees such as the LGBT Caucus, Alumni gatherings, the Commission on Student Affairs, Order of the Gavel, etc.;",
                 "Work as an administrator on tasks that cannot be referred to a particular committee as stated by the bylaws or by necessity;",
                 "Delegate all information, tasks, and plans to the appropriate officers and to oversee all duties of the officers;",
                 "Chair all Engagement Committee meetings unless otherwise delegated;",
                 "Generate a weekly agenda for Engagement Committee meeting proceedings;",
                 "Cultivate leadership traits of Engagement Committee members in their charge and the organizational development of HokiePRIDE;",
                 "Create committees and appoint committee chairs for specific programs sanctioned by the Engagement Committee;",
                 "Oversee and help with the composition of the annual budget with the Vice President and Finance Chair; and",
                 "Co-manage the GobblerConnect site with the Web & Technology Chair.",
               ],
    "strengths": ["Woo",
                  "Individualization",
                  "Communication",
                  "Futuristic",
                  "Input"],
    "funfacts": ["I rescued an elderly cat named Munch last year, and he is now a gay icon.",
										"I am a student coordinator for the LGBTQ+ Resource Center.",
										"I have the travel bug and haven't found a cure yet.",
										"Seriously, someone tell me how to stop being obsessed with traveling.",]
  },
  {
    "id": "cp2",
    "name": "Phoebe/Panic Gregg",
    "pronouns": "They/She",
    "position": "Co-President",
    "image": "/images/faces/Panic.jpg",
    "bio": "Civil and Environmental Engineering Junior from Floyd County Virginia. Cats and cake and pans. ",
    "duties": [
                "Represent the organization and maintain contacts with the university administration, other campus organizations, and off-campus persons, organizations, and institutions;",
                 "Meet regularly with faculty advisor to coordinate official efforts of the organization;",
                 "Represent or delegate someone to represent the organization on university committees such as the LGBT Caucus, Alumni gatherings, the Commission on Student Affairs, Order of the Gavel, etc.;",
                 "Work as an administrator on tasks that cannot be referred to a particular committee as stated by the bylaws or by necessity;",
                 "Delegate all information, tasks, and plans to the appropriate officers and to oversee all duties of the officers;",
                 "Chair all Engagement Committee meetings unless otherwise delegated;",
                 "Generate a weekly agenda for Engagement Committee meeting proceedings;",
                 "Cultivate leadership traits of Engagement Committee members in their charge and the organizational development of HokiePRIDE;",
                 "Create committees and appoint committee chairs for specific programs sanctioned by the Engagement Committee;",
                 "Oversee and help with the composition of the annual budget with the Vice President and Finance Chair; and",
                 "Co-manage the GobblerConnect site with the Web & Technology Chair.",
               ],
    "strengths": ["Acheiver",
                  "Restorative",
                  "Adaptability",
                  "Learner",
                  "Self-Assurance"],
    "funfacts": [" I have visited 5 countries if you count the United States. ",
										" The first Queer book I read was 'Doc and Fluff' by Pat Califia. ",
										" I work in the Frith Engineering Lab. "],
  },
  {
    "id": "vp1",
    "name": "Ben Janosy",
    "pronouns": "He/Him",
    "position": "Co-Vice President",
    "image": "/images/faces/BenJ.jpg",
    "bio": "I'm a sophomore in Virginia Tech's Corps of Cadets, studying political science. ",
    "duties": [
                "Maintain contact with LGBTQ affiliated organizations on campus including but not limited to Queer & Trans People of Color (QTPOC), Out in STEM (OSTEM), True Colors, and the LGBT Caucus and report communication with the EC;",
                "Cultivate leadership traits of officers in their charge and the organizational development of HokiePRIDE;",
                "Act in the role of President in the event the current President cannot carry out their duties;",
                "Onboard all new officers using provided materials;",
                "Manage and delegate tasks to interns; and",
                "Work with the President and Finance Chair to compile the annual budget.",
               ],
    "strengths": ["Strategic",
                  "Ideation",
                  "Input",
                  "Learner",
                  "Acheiver"],
    "funfacts": [
                  "I was born in Russia.",
                  "I'm from Wheaton, Illinois.",
                  "I was a varsity swimmer."
                ],
  },
  {
    "id": "vp2",
    "name": "Kinsey Cox",
    "pronouns": "She/They",
    "position": "Co-Vice President",
    "image": "/images/faces/Kinsey.jpg",
    "bio": "Hey y'all, I'm so excited to work with HokiePRIDE this year! I'm passionate about communication, social justice, and community building. When I graduate, I want to work in higher education student affairs. I look forward to meeting you this semester and if you have an idea, let us know how HokiePRIDE can help! ",
    "duties": [
                "Maintain contact with LGBTQ affiliated organizations on campus including but not limited to Queer & Trans People of Color (QTPOC), Out in STEM (OSTEM), True Colors, and the LGBT Caucus and report communication with the EC;",
                "Cultivate leadership traits of officers in their charge and the organizational development of HokiePRIDE;",
                "Act in the role of President in the event the current President cannot carry out their duties;",
                "Onboard all new officers using provided materials;",
                "Manage and delegate tasks to interns; and",
                "Work with the President and Finance Chair to compile the annual budget.",
               ],
    "strengths": ["Woo",
                  "Individualization",
                  "Communication",
                  "Futuristic",
                  "Input"],
    "funfacts": [
                  "DND Nerd",
                  "Beater in Quidditch",
                  "Really into Podcasts!!!"
                ],
  },
  {
    "id": "finance",
    "name": "RJ Loyd",
    "pronouns": "They/Them",
    "position": "Finance Chair",
    "image": "/images/faces/RJ.jpg",
    "bio": "Hi everyone, I'm very excited to work with HokiePRIDE this year! I'm a sophomore physics major with an astronomy minor. Feel free to come talk to me if you ever see me in the center or out and about. I'm looking forward to meeting everyone!  ",
    "duties": [
                "Work with the President and Vice President to compile the annual budget;",
                "Manage HokiePRIDEs proxy to the Student Budget Board;",
                "Attend all Student Budget Board meetings or delegate this responsibility as needed;",
                "Receive and disburse all money on behalf of the organization under the direction of the EC;",
                "Bring any deviations from the budget exceeding $50, or which would require review by the Student Budget Board, to the EC first;",
                "Record the acceptance of all money in a permanent running account according to the policies of the uniform accounting system;",
                "Regularly update the EC with transactions and the status of our accounts and budget;",
                "Have all vouchers and other instruments for the payments of money drawn in the name of the organization and signed by the President, Finance Chair, and/or Advisor; and",
                "Be responsible for the annual funding application process."
               ],
    "strengths": ["Consistency",
                  "Harmony",
                  "Restorative",
                  "Intellection",
                  "Developer"],
    "funfacts": [
                  "My cat's name is Hobo.",
                  "I went to my first comic book shop when I was 2 years old.",
                  "I love to rock Dad shirts.",
                  "My favorite sports are hockey and Battlebots.",
                ],
  },
  {
    "id": "webtech",
    "name": "Lexi Flad",
    "pronouns": "She/They",
    "position": "Web & Technology Chair",
    "image": "/images/faces/Lexi.jpg",
    "bio": "I'm a Mechanical Engineering major from right here in Blacksburg, and I'm really excited to make things as nice as possible for you all going forward. I like writing, music, and games, and I can talk your ear off about anything.   ",
    "duties": [
                "Maintain and regularly update the organization's website:",
                "Update permissions and rosters of officers on our Facebook page, Facebook Group, EC listserv, General Body listserv, and Google Drive as needed when officers leave or are elected;",
                "Keep records of the contact information for all officers and advisors;",
                "Work with the Resource Manager to help maintain the Google Drive; and",
                "Co-manage the GobblerConnect site with the President."
               ],
    "strengths": ["Adaptability",
                  "Connectedness",
                  "Relator",
                  "Harmony",
                  "Input"],
    "funfacts": [
                  "Most of my friends live halfway across the world!",
                  "...",
                  "",
                  "",
                  ",,,graphic design",
                ],
  },
]
